// <auto-generated />
using ASP.Gram.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASP.Gram.Migrations
{
    [DbContext(typeof(GramDbContext))]
    [Migration("20190218003718_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASP.Gram.Models.Comments", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("Comment")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("PostID");

                    b.HasKey("ID");

                    b.HasIndex("PostID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ASP.Gram.Models.Post", b =>
                {
                    b.Property<int>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("Details");

                    b.Property<string>("ImageURL");

                    b.Property<int>("Likes");

                    b.HasKey("PostID");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostID = 1,
                            Author = "JTT",
                            Details = "Check out the orcas!",
                            ImageURL = "http://1.bp.blogspot.com/-rbBG3L514tQ/UD9eJuVrH1I/AAAAAAAAIo0/RKOGYNs0WwM/s400/Outer+Space+Wallpapers+6.jpg",
                            Likes = 0
                        },
                        new
                        {
                            PostID = 3,
                            Author = "Captain Kirk",
                            Details = "Captains log: We, have, found intelligent life on neptar.",
                            ImageURL = "http://1.bp.blogspot.com/-rbBG3L514tQ/UD9eJuVrH1I/AAAAAAAAIo0/RKOGYNs0WwM/s400/Outer+Space+Wallpapers+6.jpg",
                            Likes = 0
                        },
                        new
                        {
                            PostID = 4,
                            Author = "Legolas",
                            Details = "1 million orcs killed. Time to break out the champagne!",
                            ImageURL = "http://1.bp.blogspot.com/-rbBG3L514tQ/UD9eJuVrH1I/AAAAAAAAIo0/RKOGYNs0WwM/s400/Outer+Space+Wallpapers+6.jpg",
                            Likes = 0
                        },
                        new
                        {
                            PostID = 5,
                            Author = "John Snow",
                            Details = "I may not know much but I know how to kill white walkes!",
                            ImageURL = "http://1.bp.blogspot.com/-rbBG3L514tQ/UD9eJuVrH1I/AAAAAAAAIo0/RKOGYNs0WwM/s400/Outer+Space+Wallpapers+6.jpg",
                            Likes = 0
                        },
                        new
                        {
                            PostID = 2,
                            Author = "Miss Jackson",
                            Details = "I am for real!",
                            ImageURL = "http://1.bp.blogspot.com/-rbBG3L514tQ/UD9eJuVrH1I/AAAAAAAAIo0/RKOGYNs0WwM/s400/Outer+Space+Wallpapers+6.jpg",
                            Likes = 0
                        });
                });

            modelBuilder.Entity("ASP.Gram.Models.Comments", b =>
                {
                    b.HasOne("ASP.Gram.Models.Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
