// <auto-generated />
using ASP.Gram.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASP.Gram.Migrations
{
    [DbContext(typeof(GramDbContext))]
    partial class GramDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASP.Gram.Models.Posts", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("Comment");

                    b.Property<string>("Details");

                    b.Property<string>("ImageURL");

                    b.HasKey("ID");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Author = "JTT",
                            Details = "Check out the orcas!",
                            ImageURL = "image.jpg"
                        },
                        new
                        {
                            ID = 2,
                            Author = "Miss Jackson",
                            Details = "I am for real!",
                            ImageURL = "image2.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
